configuration: Release

platform: Any CPU

install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build: 
  - nuget restore
  # Updates the version number in the .vsixmanifest and updates the AppVeyor build number to match
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build:
  project: Viasfora.sln
  verbosity: minimal

branches:
  only:
    - develop

artifacts:
  - path: Viasfora\bin\$(configuration)\Winterdom.Viasfora.vsix
    name: Viasfora

# Pushes the compiled vsix to artifacts and publishes it to vsixgallery.com
#  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
