version: 2.1.{build}

branches:
  only:
    - master
    - develop

configuration:
  - Release
platform:
  - Any CPU

artifacts:
  - path: Viasfora\bin\$(configuration)\Winterdom.Viasfora.vsix
    name: Viasfora
