version: 2.1.{build}

branches:
  only:
    - master
    - develop

configuration: Release
platform: AnyCPU

artifacts:
  - path: Viasfora\bin\$(configuration)\Winterdom.Viasfora.vsix
    name: Viasfora
